version: "3"

services:
  rest:
    build:
      context: ./rest
    ports:
      - 5001:5000
    volumes:
      - ./rest/src:/app

  ui:
    build:
      context: ./ui
    environment:
      - REST_SERVER=http://rest:5000
    ports:
      - 5000:5000
    volumes:
      - ./ui/src:/app
